// ============================================================================
// FILE: src/types/landing.ts
// PURPOSE: Landing page type definitions (storefront-verified fields only)
//
// [v4 cleanup — 2026-05-15]
//   - Removed `ProductsBlock`, `ProductsSectionConfig`, `ProductsSection`
//   - Removed `products?: ProductsSection` from `TenantLandingConfig`
//   - Rationale: products-on-landing was deprecated in Phase 3 (2026-05-13).
//     `store/[slug]/page.tsx` only gates on `hero.enabled`. Products live
//     at `/products` page only. The `products` branch was persisted in DB
//     but never consumed by any render path.
//
// [TEMPLATE MIGRATION — 2026-09-11]
//   - `HeroBlock` → `TemplateId` (single canonical form, no legacy union).
//   - Field `hero.block` → `hero.template` (mirrors BE validator/grandfathering).
//   - Dispatcher (templates/template.tsx) lazy-loads template{N}.tsx based
//     on this id.
//   - BE validator regex: '^template[1-9][0-9]*$' — no more "hero{n}" or
//     "block{n}" accepted.
//
// No backward-compat: legacy data is rejected and dev DB is reset.
//
// Note: `hero.title`, `hero.subtitle`, `hero.config.ctaText`, and
// `hero.config.ctaLink` are RETAINED in `HeroSection` / `HeroSectionConfig`
// because the template dispatcher uses them as a fallback chain when the
// tenant-root fields are empty. They have no Studio UI but are still
// rendered if present in legacy data.
// ============================================================================

// ==========================================
// TEMPLATE ID TYPES
// ==========================================

/**
 * Canonical template ID format. Generated by template-options.ts and written
 * by studio on save. Example: "template1", "template2", ..., "template25".
 */
type NewTemplateId = `template${number}`;

/**
 * Union accepted by config. Single canonical form — legacy "hero{n}" and
 * transitional "block{n}" were dropped in the Sept 2026 migration; data
 * carrying those values must be reset (dev mode).
 *
 * BE validator AJV regex: '^template[1-9][0-9]*$'
 */
export type TemplateId = NewTemplateId;

// ==========================================
// SECTION CONFIG INTERFACES
// ==========================================

interface HeroSectionConfig {
  ctaText?: string;
  ctaLink?: string;
}

// ==========================================
// SECTION INTERFACES
// ==========================================

export interface HeroSection {
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  /** Template variant ID. Single canonical form: `template${n}`. */
  template?: TemplateId;
  config?: HeroSectionConfig;
}

// ==========================================
// MAIN CONFIG
// ==========================================

export interface TenantLandingConfig {
  enabled: boolean;
  hero?: HeroSection;
}